on:
  workflow_call:
    inputs:
      upload-db:
        description: Whether or not to upload db artifact
        required: false
        default: false
        type: boolean

jobs:
  apply_corrections:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch corrections.json
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd geoipdb
          gh release download geoipdb -p corrections.json

      - name: Make new corrections.json
        run: |
          set -e
          cd geoipdb
          ./make-corrections >corrections-new.json
          diff -u corrections.json corrections-new.json || mv corrections-new.json corrections.json

      - name: Fetch deps
        run: |
          set -e
          sudo apt-get -q update
          sudo apt-get install -y make

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.6

      - name: Build mmdb-editor
        run: |
          set -e
          git clone https://github.com/iglov/mmdb-editor.git
          cd mmdb-editor
          make linux-amd64
          cd ..

      - name: Fetch base db
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          cd geoipdb
          gh release download geoipdb -p iplocation-base.mmdb.gz
          gunzip iplocation-base.mmdb.gz

      - name: Apply corrections
        run: |
          set -e
          cd geoipdb
          ../mmdb-editor/bin/mmdb-editor* -d corrections.json -i iplocation-base.mmdb -o iplocation.mmdb
          gzip iplocation.mmdb

      - name: Upload correction artifact
        if: ${{ !inputs.upload-db }}
        uses: actions/upload-artifact@v4
        with:
          name: corrections
          path: |
            geoipdb/corrections.json

      - name: Upload corrections and db artifacts
        if: inputs.upload-db
        uses: actions/upload-artifact@v4
        with:
          name: iplocation
          path: |
            geoipdb/corrections.json
            geoipdb/iplocation.mmdb.gz
