name: cron
on:
  schedule: 
    #- cron: '30 0 2 * *' # 12:30 am, 2nd day of the month
    - cron: '00 20 19 * *' # 8 pm UTC, 19th day of the month
  workflow_dispatch:

jobs:
  get_new_base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch new base
        run: |
          curl -o iplocation-base.mmdb.gz https://download.db-ip.com/free/dbip-city-lite-$(date +%Y-%m).mmdb.gz

      - name: Upload it to the geoipdb release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload geoipdb iplocation-base.mmdb.gz --clobber

  apply_corrections:
    needs:
      - get_new_base
    uses: ./.github/workflows/apply-corrections.yml 
    with:
      upload-db: true
    secrets: inherit
